In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np

import geoengine as ge

/home/droenner/git/geoengine-python/env/lib/python3.10/site-packages/geopandas/_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
ge.initialize("http://localhost:3030/api", credentials=("admin", "geoserver"))

In [ ]:
nrw_crops_2021 = gpd.read_file("~/Downloads/eurocrop/NRW/DE_NRW_2021_EC21.shp")
nrw_crops_2021

In [4]:
nrw_crops_2021["points"]= nrw_crops_2021.centroid
nrw_crops_2021.set_geometry("points", inplace=True)
nrw_crops_2021

,ID,INSPIRE_ID,FLIK,AREA_HA,CODE,CODE_TXT,USE_CODE,USE_TXT,D_PG,CROPDIV,EFA,ELER,WJ,DAT_BEARB,EC_trans_n,EC_hcat_n,EC_hcat_c,geometry,points
0,4598773,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0544130746,1.5204,311,Winterraps,OE,Ölsaaten,N,N,N,N,2021,2021-03-12,Winter rape,winter_rapeseed_rape,3301060401,"POLYGON ((428647.740 5711831.893, 428651.689 5...",POINT (428690.027 5711938.188)
1,4598772,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0544130596,2.2812,131,Wintergerste,GT,Getreide,N,N,N,N,2021,2021-03-12,Winter barley,winter_barley,3301010401,"POLYGON ((427717.449 5710011.129, 427709.347 5...",POINT (427819.337 5710040.545)
2,4598771,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0544130402,0.8311,115,Winterweichweizen,GT,Getreide,N,N,N,N,2021,2021-03-12,Winter soft wheat,winter_common_soft_wheat,3301010101,"POLYGON ((427337.557 5710068.067, 427332.544 5...",POINT (427320.866 5710158.178)
3,5447571,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0548091835,4.7241,459,Grünland (Dauergrünland),GL,Dauergrünland,Y,N,N,Y,2021,2021-09-24,Grassland (permanent grassland),pasture_meadow_grassland_grass,3302000000,"POLYGON ((376283.353 5665431.250, 376308.653 5...",POINT (376382.931 5665589.643)
4,5447586,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0548091988,6.1005,459,Grünland (Dauergrünland),GL,Dauergrünland,Y,N,N,Y,2021,2021-09-24,Grassland (permanent grassland),pasture_meadow_grassland_grass,3302000000,"POLYGON ((376495.069 5665848.269, 376496.653 5...",POINT (376661.541 5665982.356)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732840,5452946,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0544044277,0.2245,459,Grünland (Dauergrünland),GL,Dauergrünland,Y,N,N,N,2021,2021-09-28,Grassland (permanent grassland),pasture_meadow_grassland_grass,3302000000,"POLYGON ((318722.168 5716489.664, 318717.330 5...",POINT (318725.847 5716507.765)
732841,5453270,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0544053515,0.5144,459,Grünland (Dauergrünland),GL,Dauergrünland,Y,N,N,N,2021,2021-09-28,Grassland (permanent grassland),pasture_meadow_grassland_grass,3302000000,"POLYGON ((334648.317 5714560.040, 334636.516 5...",POINT (334675.862 5714607.930)
732842,5436890,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0543093342,0.7678,424,Ackergras,AF,Ackerfutter,N,N,N,N,2021,2021-09-16,Arable grass,pasture_meadow_grassland_grass,3302000000,"POLYGON ((381352.164 5720357.938, 381350.583 5...",POINT (381364.720 5720469.927)
732843,5479175,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0543123433,0.0406,459,Grünland (Dauergrünland),GL,Dauergrünland,Y,N,N,N,2021,2021-10-15,Grassland (permanent grassland),pasture_meadow_grassland_grass,3302000000,"POLYGON ((412042.260 5718477.152, 412041.754 5...",POINT (412151.911 5718571.206)
732844,5479179,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,DENWLI0543123434,0.0291,459,Grünland (Dauergrünland),GL,Dauergrünland,Y,N,N,N,2021,2021-10-15,Grassland (permanent grassland),pasture_meadow_grassland_grass,3302000000,"POLYGON ((411594.531 5718252.338, 411640.322 5...",POINT (411756.575 5718346.849)

In [8]:
nrw_crops_2021_points_code = nrw_crops_2021[["ID", "points", "CODE"]]
nrw_crops_2021_points_code

             ID                          points  CODE
0       4598773  POINT (428690.027 5711938.188)   311
1       4598772  POINT (427819.337 5710040.545)   131
2       4598771  POINT (427320.866 5710158.178)   115
233     4812468  POINT (487642.183 5695389.521)   459
234     4812470  POINT (487494.300 5694905.542)   459
...         ...                             ...   ...
732538  5337253  POINT (479700.034 5714921.726)   459
732539  5337249  POINT (479894.547 5714065.198)   459
732799  5469360  POINT (444658.845 5640227.225)   924
732800  5469482  POINT (443979.900 5639417.550)   602
732802  5480599  POINT (472522.639 5708612.229)   459

[127108 rows x 3 columns]

In [9]:
group_sample = nrw_crops_2021_points_code.groupby("CODE").sample(frac=0.1, random_state=1337, replace=True) # frac=0.1
group_sample.reset_index(inplace=True)
group_sample

        index       ID                          points  CODE
0      432716  4813338  POINT (423240.138 5723287.358)    50
1      557529  4729095  POINT (462541.800 5726611.992)    50
2      432765  4813388  POINT (442027.883 5718115.700)    50
3      432771  4813369  POINT (440373.974 5717903.564)    50
4      189320  4688965  POINT (425990.592 5709789.067)    51
...       ...      ...                             ...   ...
12698  244869  4720774  POINT (470188.409 5723707.496)   996
12699  149276  4982227  POINT (486329.113 5719741.723)   996
12700  201046  5382326  POINT (426161.724 5705935.273)   996
12701  430308  4813243  POINT (505075.818 5707280.590)   996
12702  210243  5131812  POINT (472591.278 5706373.921)   996

[12703 rows x 4 columns]

In [3]:
bounds_array = group_sample.total_bounds
xmin = bounds_array[0]
ymin = bounds_array[1]
xmax = bounds_array[2]
ymax = bounds_array[3]

,index,ID,CODE,INSPIRE_ID,geometry
0,0,4598773,311,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (428690.027 5711938.188)
1,1,4598772,131,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (427819.337 5710040.545)
2,2,4598771,115,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (427320.866 5710158.178)
3,265,4722182,459,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (431527.388 5693772.886)
4,266,4722181,459,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (431535.193 5693614.690)
...,...,...,...,...,...
49419,732423,5337105,115,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (472357.075 5696612.529)
49420,732424,5337108,115,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (472016.875 5697690.039)
49421,732425,5337107,115,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (471981.413 5696219.338)
49422,732426,5337106,411,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (471704.064 5697043.769)
49423,732802,5480599,459,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,POINT (472522.639 5708612.229)

In [5]:
sentinel2_b_scl_workflow = ge.unstable.sentinel2_band("SCL", utm_zone="UTM32N")

f410bd67-0df6-4a56-b5de-073ea2ba3c45

In [6]:
ge_point_source = ge.unstable.workflow_operators.OgrSource(str(ge_res))
ge_point_source.to_dict()

{'type': 'OgrSource',
 'params': {'data': {'type': 'internal',
   'datasetId': 'f410bd67-0df6-4a56-b5de-073ea2ba3c45'},
  'attributeProjection': None,
  'attributeFilters': None}}

In [7]:
import geoengine
    
def multiple_s2_cloud_free_bands(bands, granularity="days", window_size=1, aggregation_type="months"):
    valid_sentinel_bands = ["B01", "B02", "B03", "B04", "B05", "B06", "B07", "B08", "B8A", "B11", "B12", "SCL"]
    operators = {}

    for band in bands:
        if band not in valid_sentinel_bands and band != "NDVI":
            raise ValueError(f"Invalid band: {band}")
        
        if band == "NDVI":
            s2_cloud_free_operator = geoengine.unstable.workflow_blueprints.sentinel2_cloud_free_ndvi()
        else:
            s2_cloud_free_operator = geoengine.unstable.workflow_blueprints.sentinel2_cloud_free_band(band)

            # We could also leave out the scaling and use the I64 data directly
            #s2_cloud_free_operator = geoengine.unstable.workflow_operators.RasterTypeConversion(
            #    source=s2_cloud_free_operator,
            #    output_data_type="F32"
            #)
            #s2_cloud_free_operator = geoengine.unstable.workflow_operators.RasterScaling(
            #    source=s2_cloud_free_operator,
            #    slope = 0.0001,
            #    offset = -0.1, # this should be -0.1 but the values are too small?
            #    scaling_mode="mulSlopeAddOffset"
            #)

        monthly_s2_cloud_free_operator = geoengine.unstable.workflow_operators.TemporalRasterAggregation(
            source=s2_cloud_free_operator,
            aggregation_type=aggregation_type,
            granularity=granularity,
            window_size=window_size,
            ignore_no_data=True,
        )

        operators[band] = monthly_s2_cloud_free_operator
    
    return operators
    


sentinel_bands = ["B02", "B03", "B04", "B08", "NDVI"]
operators = multiple_s2_cloud_free_bands(sentinel_bands, granularity="months", window_size=1, aggregation_type="mean")

projected_points = geoengine.unstable.workflow_operators.Reprojection(ge_point_source, target_spatial_reference="EPSG:32632")

points_with_s2_cloud_free = geoengine.unstable.workflow_operators.RasterVectorJoin(
    raster_sources=[x for x in operators.values() ],
    vector_source=projected_points,
    new_column_names=[x for x in operators.keys()],
)

points_with_s2_cloud_free.to_dict()

{'type': 'RasterVectorJoin',
 'params': {'names': ['B02', 'B03', 'B04', 'B08', 'NDVI'],
  'temporalAggregation': 'none',
  'featureAggregation': 'mean'},
 'sources': {'vector': {'type': 'Reprojection',
   'params': {'targetSpatialReference': 'EPSG:32632'},
   'sources': {'source': {'type': 'OgrSource',
     'params': {'data': {'type': 'internal',
       'datasetId': 'f410bd67-0df6-4a56-b5de-073ea2ba3c45'},
      'attributeProjection': None,
      'attributeFilters': None}}}},
  'rasters': [{'type': 'TemporalRasterAggregation',
    'params': {'aggregation': {'type': 'mean', 'ignoreNoData': True},
     'window': {'granularity': 'months', 'step': 1}},
    'sources': {'raster': {'type': 'Expression',
      'params': {'expression': ' if (B == 3 || (B >= 7 && B <= 11)) { NODATA } else { A }',
       'outputType': 'U16',
       'mapNoData': False},
      'sources': {'a': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:B02'}}},
       'b': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:SCL'}}}}}}},
   {'type': 'TemporalRasterAggregation',
    'params': {'aggregation': {'type': 'mean', 'ignoreNoData': True},
     'window': {'granularity': 'months', 'step': 1}},
    'sources': {'raster': {'type': 'Expression',
      'params': {'expression': ' if (B == 3 || (B >= 7 && B <= 11)) { NODATA } else { A }',
       'outputType': 'U16',
       'mapNoData': False},
      'sources': {'a': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:B03'}}},
       'b': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:SCL'}}}}}}},
   {'type': 'TemporalRasterAggregation',
    'params': {'aggregation': {'type': 'mean', 'ignoreNoData': True},
     'window': {'granularity': 'months', 'step': 1}},
    'sources': {'raster': {'type': 'Expression',
      'params': {'expression': ' if (B == 3 || (B >= 7 && B <= 11)) { NODATA } else { A }',
       'outputType': 'U16',
       'mapNoData': False},
      'sources': {'a': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:B04'}}},
       'b': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:SCL'}}}}}}},
   {'type': 'TemporalRasterAggregation',
    'params': {'aggregation': {'type': 'mean', 'ignoreNoData': True},
     'window': {'granularity': 'months', 'step': 1}},
    'sources': {'raster': {'type': 'Expression',
      'params': {'expression': ' if (B == 3 || (B >= 7 && B <= 11)) { NODATA } else { A }',
       'outputType': 'U16',
       'mapNoData': False},
      'sources': {'a': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:B08'}}},
       'b': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:SCL'}}}}}}},
   {'type': 'TemporalRasterAggregation',
    'params': {'aggregation': {'type': 'mean', 'ignoreNoData': True},
     'window': {'granularity': 'months', 'step': 1}},
    'sources': {'raster': {'type': 'Expression',
      'params': {'expression': ' if (B == 3 || (B >= 7 && B <= 11)) { NODATA } else { (A - B) / (A + B) }',
       'outputType': 'F32',
       'mapNoData': False},
      'sources': {'a': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:B08'}}},
       'b': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:B04'}}},
       'c': {'type': 'GdalSource',
        'params': {'data': {'type': 'external',
          'providerId': '5779494c-f3a2-48b3-8a2d-5fbba8c5b6c5',
          'layerId': 'UTM32N:SCL'}}}}}}}]}}

In [8]:
workflow = geoengine.register_workflow(points_with_s2_cloud_free.to_workflow_dict())
workflow

16cc0b27-034a-536a-bc7c-2cb297a0cbdb

In [9]:
import datetime

start_dt = datetime.datetime(2021, 4, 1, 0, 0, 0, tzinfo=datetime.timezone.utc)
end_dt = datetime.datetime(2021, 10, 30, 0, 0, 0, tzinfo=datetime.timezone.utc)


gp_res = await workflow.vector_stream_into_geopandas(
    geoengine.QueryRectangle(
        spatial_bounds=geoengine.BoundingBox2D(
            xmin=xmin,
            ymin=ymin,
            xmax=xmax,
            ymax=ymax,
        ),
        time_interval=geoengine.TimeInterval(
            start=start_dt,
            end=end_dt,
        ),
        resolution=geoengine.SpatialResolution(
            100.0,
            100.0,
        ),
        srs="EPSG:32632",
))

gp_res.to_file("gp_res_100_frac1.gpkg", driver="GPKG")
gp_res

,INSPIRE_ID,index,ID,B02,CODE,B04,B03,B08,NDVI,geometry,time_start,time_end
0,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,0,0,528.0,311,516.0,724.0,3818.0,0.412993,MULTIPOINT (428690.027 5711938.189),2021-04-01 00:00:00+00:00,2021-05-01 00:00:00+00:00
1,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,1,1,765.0,131,665.0,875.0,3778.0,0.391652,MULTIPOINT (427819.337 5710040.545),2021-04-01 00:00:00+00:00,2021-05-01 00:00:00+00:00
2,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,2,2,470.0,115,590.0,604.0,2433.0,0.237053,MULTIPOINT (427320.866 5710158.178),2021-04-01 00:00:00+00:00,2021-05-01 00:00:00+00:00
3,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,265,3,349.0,459,474.0,524.0,2533.0,0.211571,MULTIPOINT (431527.388 5693772.886),2021-04-01 00:00:00+00:00,2021-05-01 00:00:00+00:00
4,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,266,4,339.0,459,433.0,538.0,2784.0,0.205698,MULTIPOINT (431535.193 5693614.690),2021-04-01 00:00:00+00:00,2021-05-01 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
345949,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,732423,49419,456.0,115,756.0,796.0,2952.0,0.270542,MULTIPOINT (472357.075 5696612.529),2021-10-01 00:00:00+00:00,2021-11-01 00:00:00+00:00
345950,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,732424,49420,433.0,115,772.0,764.0,2907.0,0.243638,MULTIPOINT (472016.875 5697690.039),2021-10-01 00:00:00+00:00,2021-11-01 00:00:00+00:00
345951,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,732425,49421,410.0,115,669.0,758.0,3570.0,0.291890,MULTIPOINT (471981.413 5696219.338),2021-10-01 00:00:00+00:00,2021-11-01 00:00:00+00:00
345952,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,732426,49422,342.0,411,517.0,598.0,3445.0,0.251615,MULTIPOINT (471704.064 5697043.769),2021-10-01 00:00:00+00:00,2021-11-01 00:00:00+00:00
345953,https://geodaten.nrw.de/id/inspire-lu-ts/exist...,732802,49423,312.0,459,398.0,646.0,3821.0,0.356315,MULTIPOINT (472522.639 5708612.229),2021-10-01 00:00:00+00:00,2021-11-01 00:00:00+00:00